language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t polux0/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e=CI polux0/react-test npm test -- --coverage

after_success:
    - docker build -t polux0/simple-client ./client
    - docker build -t polux0/simple-nginx ./nginx
    - docker build -t polux0/multi-server ./server
    - docker build -t polux0/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
    - docker push polux0/simple-client
    - docker push polux0/simple-nginx
    - docker push polux0/multi-server
    - docker push polux0/multi-worker